### ISSUE TITLE
Accurate statement about the issues fixed between Kaggle and BDG2

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/building-data-genome-project-2#10]
I have the following passage in the paper -- is it correct?

The data contained in this repository has several differences from that found on the Kaggle competition website. These were issues that were detected in the midst of the competition and were fixed in this updated data set. The first difference is that the BDG2.0 data set only has timestamps that are in the local time zone, including the weather data. The weather data released in the Kaggle competition had a timestamp that was set to UTC and the contestants had to come up with ways to find the right alignment for the weather data in order to use it properly. The other issue fixed was a conversion mistake in which Site X was not properly converted to \emph{kWh$_{sum}$} and was instead left in its raw form. This conversion has fixed in this data set.

**Comment by anjukan** [comment]
Looks accurate to me and I believe that X should be 0 (Panther). I think Table 4 also needs to be updated to reflect the original raw units of kBTU.

**Comment by ponybiam** [comment]
That's correct. And Anjukan is right, "Site X" is Site 0 (Panther).

**Comment by cmiller8** [comment]
Great, thanks!

**Comment by cmiller8** [comment]
I need to update this based on the new conversions.
