### ISSUE TITLE
Change all water meters from gallons to liters

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/building-data-genome-project-2#13]
Change all non-energy meters to liters from gallons

**Comment by ponybiam** [comment]
This was done in [ashrae-great-energy-predictor-3-internal-data-prep](https://github.com/buds-lab/ashrae-great-energy-predictor-3-internal-data-prep) repository, there is a pull request to merge the conversion branch ([BDG2-conversion](https://github.com/buds-lab/ashrae-great-energy-predictor-3-internal-data-prep/tree/BDG-conversion), I'm pushing the most recent commit). `raw` data is being upload in this repository.
