### ISSUE TITLE
Site Moose converted from MJ, not KJ

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/building-data-genome-project-2#20]
Just discovered that I messed up one more conversion!

Chilled Water and Elec for Moose should be converted from Megajoules (MJ) and not kilojoules (KJ)

![image](https://user-images.githubusercontent.com/193675/83109536-287d8300-a0f4-11ea-9ac7-34e4c8a1fe3a.png)

**Comment by ponybiam** [comment]
I'm on it. I've already corrected units, now I'm re-running the affected notebooks to correct the figures.

**Comment by cmiller8** [comment]
yay! thanks!
