### ISSUE TITLE
zeros in electricity_cleaned.csv

### ISSUE THREAD

**Issue by david-waterworth** [buds-lab/building-data-genome-project-2#22]
The `10_Cleaned-dataset.ipynb` contains code to convert `electricity.csv` -> `electricity_cleaned.csv` by replacing the zeros with NaN. But when I checked out `electricity_cleaned.csv` it contains the original zeros?

Plus at first glace many sites don't have data from the earlier date in the file, ideally the earliest date where data is available by site would be included in the metadata?

Also maybe it's because I cloned the repo or didn't have git-lfs installed first, but I had to do a bit of googling to work out how to fetch the csv files. It might pay to add some details on LFS in the readme?

**Comment by ponybiam** [comment]
Thank you David, I will check it out.

**Comment by ponybiam** [comment]
- `electricity_cleaned.csv` have been updated.
- A wiki page on Git-LFS has been created.
- Date of availabe data in `metadata.csv` suggestion has been moved to another issue and will be discussed with the team.

Thank you @david-waterworth
