### ISSUE TITLE
misaligned timestamps?

### ISSUE THREAD

**Issue by david-waterworth** [buds-lab/building-data-genome-project-2#23]
I loaded the `weather.csv` and `electricity.csv` files into Pandas. The timestamp fields seem to be inconsistent. 

In `weather.csv` for `site_id="Hog"` there are two entries for `2017-11-05` (non-duplicates) due I assume to DLS end. There is also a missing entry for `2017-03-12 02:00` on DLS start.

But the electricity.csv contains 24 records per day, there is no duplicates record on 2017-11-05 and no missing on 2017-03-12 

So it appears weather.csv is wall clock time in the local timezone, and electricity is perhaps standard time? 

I noticed in particular in `11_Models.ipynb` you join the data and weather datasets on timestamp but you haven't added an index on these columns. If you add an index the join will fail. But probably of more concern, I think the temperature and electricity will be shifted by 1 hour for half the year?

**Comment by ponybiam** [comment]
Thank you David, I will check it out.

**Comment by david-waterworth** [comment]
@ponybiam any update on this? I've been doing the following, I'm not sure it's correct or the best approach.

```
import pandas as pd
import numpy as np

meters = pd.read_csv("../data/meters/raw/electricity.csv", index_col="timestamp") # don't parse dates
weather = pd.read_csv("../data/weather/weather.csv", index_col=("timestamp","site_id")) # don't parse dates
metadata = pd.read_csv("../data/metadata/metadata.csv", index_col="building_id")

building_id = "Panther_parking_Lorriane"
site_id = "Panther"

# create a new index in correct timezone - requires original data to have no gaps!
electricity = pd.Series(
    meters[building_id].values, 
    index=pd.date_range(meters[building_id].index[0],meters[building_id].index[-1], tz=metadata.loc[building_id,"timezone"], freq='60T')).rename("electricity")

# parse and localise weather data to correct timezone. Requires use of ambiguous='infer'
idx = pd.IndexSlice
weather = weather.loc[idx[:,"Panther"],:]
weather.index=pd.to_datetime(weather.index.get_level_values(0)).tz_localize(tz, ambiguous='infer')
weather.index.freq='60T'

# can now create an aligned dataframe
df = pd.concat([electricity,weather],axis=1)
```

In general, storing timestamps from different timezones in the same pandas dataframe is problematic. pd.DatetimeIndex has to have a single timezone. This means in general I've found it easier to store the data in csv using UTC and then localize.

**Comment by ponybiam** [comment]
Dear @david-waterworth ,

a new weather data set have been add, [`weather_UTC.csv`](https://github.com/buds-lab/building-data-genome-project-2/blob/master/data/weather/weather_UTC.csv). This is all in UTC time and has  a `site_timezone` feature to localize it (is the same one in metadata). In the following days I'll be working on correcting the original `weather.csv`, so I'm keeping this issue open.

Thank you very much for your feedback.

**Comment by david-waterworth** [comment]
I think the issue though is the meter data is localised but not normalised, the weather data is both localised and normalised. Even if the weather data is in UTC it cannot be joined to the meter data since it is local but doesn't include a dls offset. This seems common, for whatever reason electricity meters don't adjust their timestamp at DLS start / end.

The code below for example will denormalise - i.e. it will subtract 1 hour from summer times, then convert to a naive datetime. This is the form that the meter data is in.

```
if __name__ == "__main__":
    from datetime import datetime, timedelta
    from pytz import timezone
    import pytz

    tz = pytz.timezone("Australia/Sydney")
    fmt = '%Y-%m-%d %H:%M:%S %Z%z'

    summer = tz.localize(datetime(2020, 2, 1))
    print(summer.strftime(fmt))

    winter = tz.localize(datetime(2020, 6, 1))
    print(winter.strftime(fmt))

    print(((winter - winter.dst()).replace(tzinfo=None)).strftime(fmt))
    print(((summer - summer.dst()).replace(tzinfo=None)).strftime(fmt))

```

**Comment by david-waterworth** [comment]
Oh I see, you have "denormalised" the weather data timestamps - that's fine.

**Comment by ponybiam** [comment]
Yes, weather timestamp have been modified. Thank you very much for your feedback @david-waterworth
