### ISSUE TITLE
Add available data start-date in metadata

### ISSUE THREAD

**Issue by ponybiam** [buds-lab/building-data-genome-project-2#24]
Should we add a feature with the date in which data starts being available for each building? a lot of them have missing values at the begginig of the period and it was suggested by an user that may be useful.

**Comment by cmiller8** [comment]
I think giving a `start date` as a meta column would imply that this was a variable attribute -- the defaults is that all buildings have the same time range, but some had missing data at the beginning. Let's not add, but let the users see that some buildings have missing data at the beginning.
