### ISSUE TITLE
Where did the weather data come from for Shrew and Swan?

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/building-data-genome-project-2#5]
@anjukan @ponybiam --- this is from the paper -- I guess someone got the weather data for those last two sites?

![image](https://user-images.githubusercontent.com/193675/80909106-3a1f7500-8d58-11ea-8bd9-5dd9a268362e.png)

**Comment by anjukan** [comment]
The weather station ISD station codes look correct. Just cross-checked. However, quick question on Swan, the site name is listed as "Anonymous" in Table 1 of the paper. Location is N/A. The ISD station code gives away the location. Why is this listed as Anonymous? Is this an issue?

**Comment by cmiller8** [comment]
Good call - I think having the weather file will give the location, you're right - but the site will officially remain anonymous. We haven't requested permission to make the official identity of the site public yet
