### ISSUE TITLE
Measurement Units Recheck

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/building-data-genome-project-2#6]
@anjukan -- is there a reason that `Bear` and `Hog` are left blank -- is it because you didn't know what those units were? 

![image](https://user-images.githubusercontent.com/193675/80931347-d21a6e80-8deb-11ea-809d-178021483917.png)

**Comment by anjukan** [comment]
Hi @cmiller8 , I pulled the values in this table from the google shared drive. I just double checked these sites, I did not do the original data processing for these two sites (I believe Samy looked after these sites so can confirm). However, I looked at the notebook that performed the standardization of units and there were no steps performed on either site. This suggests that the units are defaults, i.e. kWh_sum for Bear and kWh_sum for Hog for elec, chilled water and steam (but please verify).

**Comment by cmiller8** [comment]
@samy101 -- Did you help Anjukan with the unit conversion for these sites?

**Comment by samy101** [comment]
@cmiller8, Yes, I think. Probably, we missed those two sites because of missing unit information on the google sheet.

**Comment by cmiller8** [comment]
@samy101 -- the Bear data set was your responsibility -- can you check to see if the unit is `kWh_sum` please?

**Comment by cmiller8** [comment]
Nevermind -- I found the email chain and asked Paul to double check for Bear

**Comment by cmiller8** [comment]
@ponybiam -- after an investigation it seems that the chilled water and steam meters for `hog` didn't get converted before the Kaggle competition :(  -- the competitors didn't pick up on that because this was one of the private data sets. Not a huge deal since all the conversions were simple multipliers

For `hog` - the chilled water meters are in the units of *Tons* and need to be converted to *kWh_sum* and the steam meters are currently in units of *lbs/hour* and need to be converted as well using the conversion factors from the paper.

**Comment by cmiller8** [comment]
For the `bear` data set -- the elec meters are confirmed to be in *kW_avg* which is automatically converted to *kWh_sum*  -- so we're ok. I will update the table.

**Comment by cmiller8** [comment]
@ponybiam -- let me double confirm all the units of all the sites so we can sure that everything is converted properly and you'll only have to do the conversion process one more time

**Comment by ponybiam** [comment]
Perfect, let me know and I'll convert it to the correct units. I'll have to run all the notebooks again to update them, but if are only _chilledwater_ and _steam_ meters it shouldn't take that long.

**Comment by cmiller8** [comment]
Still working on rechecking and will be done by Saturday

**Comment by cmiller8** [comment]
@ponybiam -- I ran into some more stuff that we should chat about. Let's set up a call before we continue the conversion stuff. :)

**Comment by ponybiam** [comment]
Here's what we concluded on our meeting:

- A `kaggle` data set will be added to this repository, with the 2017 data from the [competition](https://www.kaggle.com/c/ashrae-energy-prediction) (this was the data used for the public leaderboard). 
- `raw` data will have all units corrected (energy meters in KWh and volume meters in litres)
- a `cleaned` data folder will be created: outliers and continuous zero-readings longer than 24 hours will be removed.

This issue is being closed and I will be updating Issue #11.
