### ISSUE TITLE
"Mandatory" meta data?

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/building-data-genome-project-2#7]
@anjukan -- You mentioned in your part that "For the metadata of the buildings, it was deemed that \texttt{square$\_$feet}, \texttt{primary$\_$use}, \texttt{year$\_$built} and \texttt{floor$\_$count} would be the only mandatory attributes."

Does this mean these were the filters for the Kaggle competition? I'm surprised that we required `floor count` and `year built` as mandatory.

@ponybiam -- there are tons of buildings in the BDG2 that don't have these two features, so I'm guessing we didn't make those same filtering steps?

**Comment by anjukan** [comment]
To clarify, this wasn't a filtering step but these were the only meta data features (together with lat and lng) that were kept with all other columns being dropped. Rows were not dropped if there was no data for either `floor_count` or `year_built`.

**Comment by ponybiam** [comment]
BDG2 metadata has ALL the features form [_merged metadata_](https://github.com/buds-lab/ashrae-great-energy-predictor-3-internal-data-prep/tree/master/data/merged/meta). Some of them are mostly missing values:

| Feature               | Missings |
|-----------------------|----------|
| building_id           | 0.00     |
| site_id               | 0.00     |
| primaryspaceusage     | 1.28     |
| sqft                  | 0.00     |
| lat                   | 10.88    |
| lng                   | 10.88    |
| electricity           | 3.55     |
| hotwater              | 88.69    |
| chilledwater          | 66.08    |
| steam                 | 77.38    |
| water                 | 91.08    |
| irrigation            | 97.74    |
| solar                 | 99.69    |
| gas                   | 89.18    |
| yearbuilt             | 50.06    |
| numberoffloors        | 73.04    |
| sub_primaryspaceusage | 1.28     |
| date_opened           | 98.72    |
| energystarscore       | 90.04    |
| eui                   | 81.72    |
| heatingtype           | 86.86    |
| industry              | 64.61    |
| leed_level            | 91.69    |
| occupants             | 85.94    |
| rating                | 88.75    |
| site_eui              | 90.04    |
| source_eui            | 90.04    |
| sqm                   | 73.29    |
| subindustry           | 64.61    |
| timezone              | 0.00     |

**Comment by cmiller8** [comment]
got it -- thanks!
