### ISSUE TITLE
Why did Swan not get added to the Kaggle competition?

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/building-data-genome-project-2#8]
@anjukan -- you have any idea why the `Swan` data set was never added to the Kaggle competition data set?

**Comment by anjukan** [comment]
I just had a look at the final metadata and meter data. We did submit meter data for Swan to Kaggle. It looks like they decided not to include it with the final released set. My theory why could be that this site seems to be missing `primaryspaceusage` data (based on the submitted metadata).

**Comment by cmiller8** [comment]
Ah, I remember now! yes, they never got back to use about those metadata :( dang.
